import './globals.css'

import Navbar from "@/ui/Navbar";
import Sidebar from "@/ui/Sidebar";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Navbar/>
        <div className={"flex gap-6 md:gap-20"}>
            <div className={"h-[92vh] overflow-hidden xl:overflow-auto"}>
                <Sidebar/>
            </div>
            <div className={"mt-4 flex flex-col gap-10 overflow-auto h-[88vh] videos flex-1"}>
                {children}
            </div>
        </div>
        </body>
        </html>
    )
}
